wandb_version: 1

owner:
  desc: null
  value: electrixoul
purpose:
  desc: null
  value: personal_test
timestamp:
  desc: null
  value: 2025-04-29_18-08-34
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745921315.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      - 37
      - 62
      4: 3.10.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
