wandb_version: 1

experiment:
  desc: null
  value: mnist_sae_training
input_size:
  desc: null
  value: 784
hidden_size:
  desc: null
  value: 1024
k_sparse:
  desc: null
  value: 50
num_saes:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
num_epochs:
  desc: null
  value: 5
training_batch_size:
  desc: null
  value: 128
test_batch_size:
  desc: null
  value: 64
num_examples_to_visualize:
  desc: null
  value: 10
ensemble_consistency_weight:
  desc: null
  value: 0.01
test_every_n_epochs:
  desc: null
  value: 1
timestamp:
  desc: null
  value: 2025-04-30_16-35-51
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746002153.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.16.6
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
