wandb_version: 1

test_type:
  desc: null
  value: direct_api_key_test
timestamp:
  desc: null
  value: 2025-04-29_18-07-55
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745921276.0
    t:
      1:
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
